### PR TITLE
Drop Django 1.6, 1.7, add 1.11

### PR DESCRIPTION
**Pull request by jwhitlock**
- Drop support for Django 1.6 and 1.7, and switch to 1.8+ support
- Use urlpattern syntax supported by 1.8 and later in tests
- Switch .travis.yml to matrix form, to specify specific Python versions
- Remove invalid docsinstall and double install from .travis.yml
- Add Django 1.11 and master (allowed failure) targets, and Python 3.6
- Add doc target to .travis.yml

### CODE REVIEW

**Comment by Flimm** [comment]
Huh, I just started working on the very same things a couple of minutes ago! You beat me to it, @jwhitlock . The changes look good to me. I especially like the tests that run against Django master, but that may fail. Nice one!

If you join https://github.com/jazzband, you can merge the changes yourself, assuming the tests pass.

**Comment by davidt** [comment]
Can we please not explicitly get rid of 1.6 support quite yet? I know it's EOL, but the world isn't quite off it yet. The amount of extra code required in django-pipeline to keep support is pretty minimal (just the django.test.utils fallbacks).

**Comment by jwhitlock** [comment]
@davidt The``urlpatterns`` format has changed as well.  Django 1.11 no longer supports the Django 1.7 and earlier format. It wouldn't be impossible to support both (switch on if ``pattern`` is supported), but I'm negative on the idea. Django 1.6 users can pin to 1.6.12, and should plan to update.

**Comment by jwhitlock** [comment]
I'm preparing an alt PR that retains Django 1.6 and 1.7.  We can delay retirement for a future PR...

**Comment by jwhitlock** [comment]
Closing in favor of #629

**Pull request closed without merging**
