### PR TITLE
Update compilers.rst

### PR DESCRIPTION
**Pull request by sonic182**
Added Third part libsasscompiler

### CODE REVIEW

**Comment by triat** [comment]
Hello @sonic182, thanks for your contribution! I saw that you created the libsasscompiler, I don't find any test in your repo, is there a way to make sure that it is working ? So we make sure that people who install it are not getting weird errors? Thanks :)

**Comment by sonic182** [comment]
At this moment I have no tests :/ I am using it in www.inmoduran.net
(production) and I have solve some errors before.

It is very few lines of code, but if you consider it need tests I can do
them

Thanks
Johanderson

**Comment by triat** [comment]
Sure, I'm just trying to make sure I won't put incorrect things in the repo.

I'm trying to catch up the long long list of issues and PR but I'm really new on this project, so I prefer to be a bit defensive, sorry :) 

If you think it's not too painful to write few tests, it could be great.

Let me know.

Thanks

**Comment by sonic182** [comment]
Hahaha sure it is no problem, I will put a reminder in my calendar then

Best
Johanderson

**Comment by sonic182** [comment]
Hi, I have finnaly added some tests to my repo https://github.com/sonic182/libsasscompiler and I have integrated with travis too. 

So you could check it please and do this merge if you see everything ok :+1:

**Comment by triat** [comment]
Hey @sonic182, that's awesome thanks! Everything looks good for me good job!

**Pull request merged**
