### PR TITLE
ignore_filenames

### PR DESCRIPTION
**Pull request by un1t**
Hi, I added ability to ignore some files with **ignore_filenames** option.

    PIPELINE_CSS = {
        'all': {
            'source_filenames': (
                'blocks/*/*.css',
            ),
            'ignore_filenames': (
                'blocks/*/*.ie*.css',
            ),
            'output_filename': '_all.css',
        },

### CODE REVIEW

**Comment by un1t** [comment]
I found out this commit breakes sources files order.

**Comment by un1t** [comment]
I fixed sources ordering.

**Comment by jezdez** [comment]
This needs tests and docs.

**Comment by un1t** [comment]
I switched to Gulp, so I'm not interested in this fix anymore.

**Pull request closed without merging**
