### PR TITLE
Improved packager.compile() to handle s3 storage when compiler generates output to the local one.

### PR DESCRIPTION
**Pull request by thomasyip**
This patch resolves the problem by copying the compiled file into the packager (s3) storage.

### CODE REVIEW

**Comment by peec** [comment]
+1 , very needed fix so S3 works.

**Comment by thomasyip** [comment]
See also, issue: https://github.com/cyberdelia/django-pipeline/issues/473 and pr: https://github.com/cyberdelia/django-pipeline/pull/475

**Comment by peec** [comment]
If someone needs urgents fix like me:

**app/__init__.py:**
```
# Fixes S3 for pipeline...
from pipeline.packager import Packager
from django.contrib.staticfiles.finders import get_finders, find


def __monkey_compile(self, paths, force=False):
        paths = self.compiler.compile(paths, force=force)
        for path in paths:
            if not self.storage.exists(path):
                if self.verbose:
                    print("Compiled file '%s' cannot be found with packager's storage. Locating it." % path)

                source_storage = self.find_source_storage(path)
                if source_storage is not None:
                    with source_storage.open(path) as source_file:
                        if self.verbose:
                            print("Saving: %s" % path)
                        self.storage.save(path, source_file)
                else:
                    raise IOError("File does not exist: %s" % path)
        return paths

def __monkey_find_source_storage(self, path):
    for finder in get_finders():
        for short_path, storage in finder.list(''):
            if short_path == path:
                if self.verbose:
                    print("Found storage: %s" % str(self.storage))
                return storage
    return None


Packager.compile = __monkey_compile
Packager.find_source_storage = __monkey_find_source_storage
```

**Comment by SverkerSbrg** [comment]
+1 Works well for me!

**Comment by sowinski** [comment]
What need to be done to apply this fix to this branch? Is there a fork which is allready working?

**Review by cyberdelia — APPROVED** [review]

**Comment by sowinski** [comment]
@cyberdelia 
Does it mean that it will work with the code from the master branch now?

**Pull request merged**
